resolver: lts-15.0

# due to functor-infix
allow-newer: true

packages:
  - 'ghc-primop-lib'
  - 'ghc-primop-gen'
  - 'external-stg'
  - 'external-stg-util'
  - 'ghc-grin'
  - 'lambda-grin'

build:
  test-arguments:
    additional-args:
      - "--seed=11010"

ghc-options:
  external-stg: -DEXT_STG_FOR_NON_PATCHED_GHC
