resolver: nightly-2018-11-07

allow-newer: true

packages:
- 'app'
- 'lib'
#- 'sum-list'

#- 'basic'
#- 'boq-custom'
#- 'boquist-grin-bench'
#- 'miniagda'
#- 'hpp-0.6.1'

#- 'Idris-dev-1.3.1'

#- 'lambdacube-workshop-master/hello'
#- 'lambdacube-workshop-master/hello-obj'
#- 'lambdacube-workshop-master/asteroids'
#- 'lambdacube-workshop-master/lambdacube-obj'

#- 'lambdacube-quake3-master'

extra-deps:
- proteaaudio-0.7.0.1
- vect-0.4.7
- wavefront-0.7.1.1
- megaparsec-6.5.0
- cheapskate-0.1.1
- haskell-src-exts-1.21.1

- github: lambdacube3d/lambdacube-ir
  commit: 8a0a17abedc9d6b46b41d744c1a2be53efa6336b
  subdirs:
    - lambdacube-ir.haskell

- github: lambdacube3d/lambdacube-gl
  commit: 297828bdcf105c5942ed0e43d9f28130f543f34c

- github: lambdacube3d/lambdacube-compiler
  commit: dc10dc255638b86f4a20a29a1b492e2415640b60

extra-path:
- /home/csaba/haskell/grin-compiler/ghc-grin/ghc-8.11.0.20200215-src/_build/stage1/bin

# Turn on system GHC
system-ghc: true
skip-ghc-check: true

dump-logs: all

build:
  keep-tmp-files: true
  #cabal-verbose: true
