resolver: lts-15.0

allow-newer: true

packages:
  - 'mini-ghc-grin'

extra-path:
  - /home/csaba/haskell/ghc-gitlab/ghc-8.11.0.20200222-src-git-toSTG/ghc-8.11.0.20200222-src/_build/stage1/bin

# Turn on system GHC
system-ghc: true
skip-ghc-check: true

dump-logs: all

build:
  keep-tmp-files: true
  #cabal-verbose: true

ghc-options:
  mini-ghc-grin: -DEXT_STG_FOR_NON_PATCHED_GHC

extra-deps:
  - async-pool-0.9.1@sha256:4015140f896c3f1652b06a679b0ade2717d05557970c283ea2c372a71be2a6a1,1605
